// AgroSmart product catalog — Seeds, Fertilizers, Crop Protection
// Each product carries trilingual name & description (en/te/hi).
const L = (en, te, hi) => ({ en, te, hi });

const I = {
  paddy: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/0b30f0467_generated_0a0c1c23.jpg",
  maize: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/a01cdcb26_generated_1e04934d.jpg",
  cotton: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/0d9723cb7_generated_97fa007f.jpg",
  tomato: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/a73050e52_generated_0f958f7c.jpg",
  chilli: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/e8b7998fa_generated_b9631284.jpg",
  groundnut: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/35e1776ec_generated_7e374f40.jpg",
  onion: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/900b5be0d_generated_f2a32f6d.jpg",
  brinjal: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/eb57a64c3_generated_107fb96b.jpg",
  okra: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/10f94a470_generated_98ce58b0.jpg",
  cucumber: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/e21532e70_generated_0ac7d984.jpg",
  carrot: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/851024961_generated_e7756ad8.jpg",
  coriander: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/de0fcc4b1_generated_6621b5da.jpg",
  sunflower: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/214a0740d_generated_8b901c88.jpg",
  soybean: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/ffdcea2a6_generated_cdc6e066.jpg",
  redgram: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/e6ad434fd_generated_7f3a08b5.jpg",
  greengram: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/9e59e7c9c_generated_6368bb88.jpg",
  blackgram: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/c6cd006e4_generated_a3bcd712.jpg",
  wheat: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/abb533676_generated_95c64cea.jpg",
  vegetable: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/829957172_generated_758afb8b.jpg",
  urea: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/500cc743f_generated_5835dc0e.jpg",
  dap: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/21a476de0_generated_59566e04.jpg",
  npk: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/76b304997_generated_da79ed41.jpg",
  potash: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/2ed8c6d2c_generated_613462cb.jpg",
  micronutrient: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/d2e5bffd6_generated_6f6a82fd.jpg",
  organic: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/a4757ef6f_generated_3dfb77b5.jpg",
  biofert: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/2ea8e3da2_generated_b219e23e.jpg",
  watersoluble: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/184a136b9_generated_da50b3db.jpg",
  biopesticide: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/274408f8f_generated_1acfcb48.jpg",
  fungicide: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/8a77e6d85_generated_6dc3edd4.jpg",
  herbicide: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/8c95fe95f_generated_e02f5afd.jpg",
  insecticide: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/6540bf13b_generated_9fba6d6d.jpg",
  plantdisease: "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/c73bc0fc4_generated_e65b9ca3.jpg",
};

export const HERO_IMAGE = "https://media.base44.com/images/public/6aa2e4ed578747937a80907f/fafeb4392_generated_f0a4fecd.jpg";

export const PRODUCTS = [
  // ---------------- SEEDS ----------------
  { id: "seed-paddy", category: "seeds", image: I.paddy,
    name: L("Paddy Seeds", "వరి విత్తనాలు", "धान के बीज"),
    desc: L("High-yield paddy variety for Kharif season.", "ఖరీఫ్ సీజన్‌కు అధిక దిగుబడి వరి విత్తనం.", "खरीफ सीज़न के लिए उच्च उपज धान बीज."),
    cropType: L("Cereal", "ధాన్యం", "अनाज"), season: L("Kharif (Jun–Jul)", "ఖరీఫ్ (జూన్–జూలై)", "खरीफ (जून–जुलाई)"),
    packSize: "1 kg", manufacturer: "AgriSeeds Co.", seller: "GreenGrow Mart", price: 120, availability: "in", delivery: "3–5 days",
    soilPh: "5.5–6.5", water: "High", germination: "85%" },
  { id: "seed-maize", category: "seeds", image: I.maize,
    name: L("Maize Seeds", "మొక్కజొన్ను విత్తనాలు", "मक्का के बीज"),
    desc: L("Hybrid maize with strong stalk and uniform cobs.", "బలమైన కాండం, ఏకరీతి కాబ్‌లతో హైబ్రిడ్ మొక్కజొన్ను.", "मजबूत डंठल और समान भुट्टे वाली संकर मक्का।"),
    cropType: L("Cereal", "ధాన్యం", "अनाज"), season: L("Kharif / Rabi", "ఖరీఫ్ / రవి", "खरीफ / रबी"),
    packSize: "1 kg", manufacturer: "Pioneer Seeds", seller: "Krishi Bazaar", price: 180, availability: "in", delivery: "3–5 days",
    soilPh: "5.8–7.0", water: "Medium", germination: "90%" },
  { id: "seed-cotton", category: "seeds", image: I.cotton,
    name: L("Cotton Seeds", "పత్తి విత్తనాలు", "कपास के बीज"),
    desc: L("Bt cotton seeds with bollworm resistance.", "బాల్‌వార్మ్ నిరోధకత కలిగిన Bt పత్తి విత్తనాలు.", "बॉलवर्म प्रतिरोधी बीटी कपास बीज।"),
    cropType: L("Cash Crop", "వాణిజ్య పంట", "नकदी फसल"), season: L("Kharif (May–Jun)", "ఖరీఫ్ (మే–జూన్)", "खरीफ (मई–जून)"),
    packSize: "750 g", manufacturer: "CottonLife", seller: "AgriHub", price: 450, availability: "in", delivery: "4–6 days",
    soilPh: "6.0–7.5", water: "Medium", germination: "88%" },
  { id: "seed-tomato", category: "seeds", image: I.tomato,
    name: L("Tomato Seeds", "టమాటో విత్తనాలు", "टमाटर के बीज"),
    desc: L("Disease-tolerant tomato with high fruit set.", "వ్యాధి నిరోధకత, అధిక పంట కలిగిన టమాటో.", "रोग सहनशील, उच्च फलन वाली टमाटर।"),
    cropType: L("Vegetable", "కూరగాయ", "सब्ज़ी"), season: L("All seasons", "అన్ని సీజన్లు", "सभी सीज़न"),
    packSize: "5 g", manufacturer: "VegFresh Seeds", seller: "GreenGrow Mart", price: 90, availability: "in", delivery: "2–4 days",
    soilPh: "6.0–6.8", water: "Medium", germination: "92%" },
  { id: "seed-chilli", category: "seeds", image: I.chilli,
    name: L("Chilli Seeds", "మిరప విత్తనాలు", "मिर्च के बीज"),
    desc: L("High pungency red chilli for dry and fresh use.", "ఎండబెట్టడానికి, తాజా వాడుకకు అధిక కారం మిరప.", "सूखी और ताजी उपयोग के लिए तीखी लाल मिर्च।"),
    cropType: L("Spice", "సుగంధ ద్రవ్యం", "मसाला"), season: L("Kharif / Rabi", "ఖరీఫ్ / రవి", "खरीफ / रबी"),
    packSize: "10 g", manufacturer: "SpiceGrow", seller: "Krishi Bazaar", price: 140, availability: "in", delivery: "3–5 days",
    soilPh: "6.0–7.0", water: "Medium", germination: "85%" },
  { id: "seed-groundnut", category: "seeds", image: I.groundnut,
    name: L("Groundnut Seeds", "వేరుశనగ విత్తనాలు", "मूंगफली के बीज"),
    desc: L("Bunch-type groundnut with high oil content.", "అధిక నూనె శాతం కలిగిన గులకర వేరుశనగ.", "उच्च तेल वाली गुच्छा प्रकार मूंगफली।"),
    cropType: L("Oilseed", "నూనె పంట", "तिलहन"), season: L("Kharif (Jun–Jul)", "ఖరీఫ్ (జూన్–జూలై)", "खरीफ (जून–जुलाई)"),
    packSize: "1 kg", manufacturer: "OilSeed India", seller: "AgriHub", price: 220, availability: "in", delivery: "3–5 days",
    soilPh: "5.5–7.0", water: "Low", germination: "80%" },
  { id: "seed-onion", category: "seeds", image: I.onion,
    name: L("Onion Seeds", "ఉల్లిపాయ విత్తనాలు", "प्याज़ के बीज"),
    desc: L("Long-day onion with good storage life.", "మంచి నిల్వ ఉండే దీర్ఘ-దిన ఉల్లిపాయ.", "अच्छी भंडारण वाली लंबी-दिन प्याज़।"),
    cropType: L("Vegetable", "కూరగాయ", "सब्ज़ी"), season: L("Rabi (Oct–Nov)", "రవి (అక్టో–నవం)", "रबी (अक्टू–नवं)"),
    packSize: "50 g", manufacturer: "VegFresh Seeds", seller: "GreenGrow Mart", price: 130, availability: "in", delivery: "2–4 days",
    soilPh: "6.0–7.0", water: "Medium", germination: "82%" },
  { id: "seed-brinjal", category: "seeds", image: I.brinjal,
    name: L("Brinjal Seeds", "వంకాయ విత్తనాలు", "बैंगन के बीज"),
    desc: L("Purple long brinjal with high yield.", "అధిక దిగుబడి కలిగిన నీలి పొడుగు వంకాయ.", "उच्च उपज वाली बैंगन।"),
    cropType: L("Vegetable", "కూరగాయ", "सब्ज़ी"), season: L("All seasons", "అన్ని సీజన్లు", "सभी सीज़न"),
    packSize: "10 g", manufacturer: "VegFresh Seeds", seller: "Krishi Bazaar", price: 110, availability: "in", delivery: "2–4 days",
    soilPh: "5.5–6.5", water: "Medium", germination: "85%" },
  { id: "seed-okra", category: "seeds", image: I.okra,
    name: L("Okra Seeds", "బెండకాయ విత్తనాలు", "भिंडी के बीज"),
    desc: L("Tender green okra with extended harvest.", "పొడిగిన కోత కలిగిన మృదువైన ఆకుపచ్చ బెండకాయ.", "लंबी कटाई वाली कोमल भिंडी।"),
    cropType: L("Vegetable", "కూరగాయ", "सब्ज़ी"), season: L("Kharif (Feb–Mar)", "ఖరీఫ్ (ఫిబ్ర–మార్)", "खरीफ (फर–मार्च)"),
    packSize: "100 g", manufacturer: "VegFresh Seeds", seller: "AgriHub", price: 95, availability: "in", delivery: "2–4 days",
    soilPh: "6.0–7.0", water: "Medium", germination: "88%" },
  { id: "seed-cucumber", category: "seeds", image: I.cucumber,
    name: L("Cucumber Seeds", "దోసకాయ విత్తనాలు", "खीरा के बीज"),
    desc: L("Parthenocarpic cucumber for uniform fruit.", "ఏకరీతి కాయ కోసం పార్థెనోకార్పిక్ దోస.", "समान फल के लिए पार्थेनोकार्पिक खीरा।"),
    cropType: L("Vegetable", "కూరగాయ", "सब्ज़ी"), season: L("Summer (Jan–Feb)", "వేసవి (జన–ఫిబ్ర)", "गर्मी (जन–फर)"),
    packSize: "50 g", manufacturer: "VegFresh Seeds", seller: "GreenGrow Mart", price: 85, availability: "in", delivery: "2–4 days",
    soilPh: "6.0–7.0", water: "High", germination: "90%" },
  { id: "seed-carrot", category: "seeds", image: I.carrot,
    name: L("Carrot Seeds", "క్యారెట్ విత్తనాలు", "गाजर के बीज"),
    desc: L("Deep orange carrot with smooth roots.", "మృదువైన వేరులతో లోతైన నారింజ క్యారెట్.", "चिकनी जड़ों वाली गहरी नारंगी गाजर।"),
    cropType: L("Vegetable", "కూరగాయ", "सब्ज़ी"), season: L("Rabi (Oct–Nov)", "రవి (అక్టో–నవం)", "रबी (अक्टू–नवं)"),
    packSize: "50 g", manufacturer: "VegFresh Seeds", seller: "Krishi Bazaar", price: 120, availability: "in", delivery: "2–4 days",
    soilPh: "6.0–7.0", water: "Medium", germination: "80%" },
  { id: "seed-coriander", category: "seeds", image: I.coriander,
    name: L("Coriander Seeds", "కొత్తిమీర విత్తనాలు", "धनिया के बीज"),
    desc: L("Aromatic coriander for leaf and seed.", "ఆకు, విత్తనం రెండింటికీ సువాసన కొత్తిమీర.", "पत्ती और बीज दोनों के लिए सुगंधित धनिया।"),
    cropType: L("Spice", "సుగంధ ద్రవ్యం", "मसाला"), season: L("Rabi (Oct–Nov)", "రవి (అక్టో–నవం)", "रबी (अक्टू–नवं)"),
    packSize: "250 g", manufacturer: "SpiceGrow", seller: "AgriHub", price: 70, availability: "in", delivery: "2–4 days",
    soilPh: "6.0–8.0", water: "Low", germination: "75%" },
  { id: "seed-sunflower", category: "seeds", image: I.sunflower,
    name: L("Sunflower Seeds", "సూర్యకాంతి విత్తనాలు", "सूरजमुखी के बीज"),
    desc: L("High oil content hybrid sunflower.", "అధిక నూనె శాతం హైబ్రిడ్ సూర్యకాంతి.", "उच्च तेल वाली संकर सूरजमुखी।"),
    cropType: L("Oilseed", "నూనె పంట", "तिलहन"), season: L("Kharif / Rabi", "ఖరీఫ్ / రవి", "खरीफ / रबी"),
    packSize: "1 kg", manufacturer: "OilSeed India", seller: "GreenGrow Mart", price: 260, availability: "in", delivery: "3–5 days",
    soilPh: "6.0–7.5", water: "Low", germination: "85%" },
  { id: "seed-soybean", category: "seeds", image: I.soybean,
    name: L("Soybean Seeds", "సోయాబీన్ విత్తనాలు", "सोयाबीन के बीज"),
    desc: L("Protein-rich soybean with good branching.", "మంచి శాఖలతో ప్రొటీన్ ఎక్కువ సోయాబీన్.", "अच्छी शाखाओं वाली प्रोटीन-युक्त सोयाबीन।"),
    cropType: L("Oilseed", "నూనె పంట", "तिलहन"), season: L("Kharif (Jun–Jul)", "ఖరీఫ్ (జూన్–జూలై)", "खरीफ (जून–जुलाई)"),
    packSize: "1 kg", manufacturer: "OilSeed India", seller: "Krishi Bazaar", price: 190, availability: "in", delivery: "3–5 days",
    soilPh: "6.0–7.0", water: "Medium", germination: "85%" },
  { id: "seed-redgram", category: "seeds", image: I.redgram,
    name: L("Tur / Red Gram Seeds", "కందుల (ఎర్ర గ్రామ్) విత్తనాలు", "अरहर (तुअर) के बीज"),
    desc: L("Drought-tolerant red gram for pulses.", "పప్పు కోసం కరువు నిరోధక కందుల.", "दलहन के लिए सूखा-सहनशील अरहर।"),
    cropType: L("Pulse", "పప్పు", "दलहन"), season: L("Kharif (Jun–Jul)", "ఖరీఫ్ (జూన్–జూలై)", "खरीफ (जून–जुलाई)"),
    packSize: "1 kg", manufacturer: "PulseFarm", seller: "AgriHub", price: 240, availability: "in", delivery: "3–5 days",
    soilPh: "6.0–7.5", water: "Low", germination: "82%" },
  { id: "seed-greengram", category: "seeds", image: I.greengram,
    name: L("Green Gram Seeds", "పెసర విత్తనాలు", "मूंग के बीज"),
    desc: L("Short-duration green gram for quick harvest.", "త్వరిత కోత కోసం స్వల్ప-వ్యవధి పెసర.", "तेज कटाई के लिए अल्प-अवधि मूंग।"),
    cropType: L("Pulse", "పప్పు", "दलहन"), season: L("Kharif / Spring", "ఖరీఫ్ / వసంత", "खरीफ / वसंत"),
    packSize: "1 kg", manufacturer: "PulseFarm", seller: "GreenGrow Mart", price: 210, availability: "in", delivery: "3–5 days",
    soilPh: "6.0–7.5", water: "Low", germination: "85%" },
  { id: "seed-blackgram", category: "seeds", image: I.blackgram,
    name: L("Black Gram Seeds", "మినుము విత్తనాలు", "उड़द के बीज"),
    desc: L("Bold-seeded black gram for high protein.", "అధిక ప్రొటీన్ కోసం పెద్ద మినుము.", "उच्च प्रोटीन के लिए बड़ी उड़द।"),
    cropType: L("Pulse", "పప్పు", "दलहन"), season: L("Kharif / Rabi", "ఖరీఫ్ / రవి", "खरीफ / रबी"),
    packSize: "1 kg", manufacturer: "PulseFarm", seller: "Krishi Bazaar", price: 230, availability: "in", delivery: "3–5 days",
    soilPh: "6.0–7.5", water: "Low", germination: "83%" },
  { id: "seed-wheat", category: "seeds", image: I.wheat,
    name: L("Wheat Seeds", "గోధుమ విత్తనాలు", "गेहूं के बीज"),
    desc: L("Lodging-resistant wheat for Rabi season.", "రవి సీజన్‌కు పడిపోకుండా ఉండే గోధుమ.", "रबी के लिए लॉजिंग-रोधी गेहूं।"),
    cropType: L("Cereal", "ధాన్యం", "अनाज"), season: L("Rabi (Nov–Dec)", "రవి (నవం–డిసం)", "रबी (नवं–दिसं)"),
    packSize: "5 kg", manufacturer: "AgriSeeds Co.", seller: "AgriHub", price: 180, availability: "in", delivery: "3–5 days",
    soilPh: "6.0–7.5", water: "Medium", germination: "90%" },
  { id: "seed-vegetable-mix", category: "seeds", image: I.vegetable,
    name: L("Vegetable Seeds Mix", "కూరగాయ విత్తనాల మిశ్రమం", "सब्ज़ी बीज मिश्रण"),
    desc: L("Assorted kitchen garden vegetable seeds.", "వివిధ అంతఃప్రాంగణ కూరగాయ విత్తనాలు.", "माली के लिए मिश्रित सब्ज़ी बीज।"),
    cropType: L("Vegetable", "కూరగాయ", "सब्ज़ी"), season: L("All seasons", "అన్ని సీజన్లు", "सभी सीज़न"),
    packSize: "20 g", manufacturer: "VegFresh Seeds", seller: "GreenGrow Mart", price: 150, availability: "in", delivery: "2–4 days",
    soilPh: "6.0–7.0", water: "Medium", germination: "85%" },

  // ---------------- FERTILIZERS ----------------
  { id: "fert-urea", category: "fertilizers", image: I.urea,
    name: L("Urea (46-0-0)", "యూరియా (46-0-0)", "यूरिया (46-0-0)"),
    desc: L("Nitrogen-rich fertilizer for vegetative growth.", "శాఖ వృద్ధికి నత్రజని ఎరువు.", "वानस्पतिक वृद्धि के लिए नाइट्रोजन उर्वरक।"),
    cropType: L("Nitrogen", "నత్రజని", "नाइट्रोजन"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "45 kg", manufacturer: "National Fertilizers", seller: "Krishi Bazaar", price: 275, availability: "in", delivery: "2–4 days" },
  { id: "fert-dap", category: "fertilizers", image: I.dap,
    name: L("DAP (18-46-0)", "DAP (18-46-0)", "DAP (18-46-0)"),
    desc: L("Phosphorus-rich basal fertilizer.", "అసలు ఎరువుగా భాస్వరం ఎక్కువ.", "बेसल फास्फोरस उर्वरक।"),
    cropType: L("Phosphorus", "భాస్వరం", "फास्फोरस"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "50 kg", manufacturer: "Fertilizers India", seller: "AgriHub", price: 1350, availability: "in", delivery: "2–4 days" },
  { id: "fert-npk", category: "fertilizers", image: I.npk,
    name: L("NPK (19-19-19)", "NPK (19-19-19)", "NPK (19-19-19)"),
    desc: L("Balanced water-soluble NPK for foliar spray.", "ఆకు పిచికారానికి సమతుల్య NPK.", "पत्ती छिडकाव के लिए संतुलित NPK।"),
    cropType: L("Complex", "సంక్లిష్ట", "मिश्रित"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "5 kg", manufacturer: "YaraVera", seller: "GreenGrow Mart", price: 1200, availability: "in", delivery: "2–4 days" },
  { id: "fert-potash", category: "fertilizers", image: I.potash,
    name: L("Potash (MOP)", "పొటాష్ (MOP)", "पोटाश (MOP)"),
    desc: L("Potassium chloride for fruit quality.", "కాయ నాణ్యతకు పొటాషియం క్లోరైడ్.", "फल गुणवत्ता के लिए पोटेशियम क्लोराइड।"),
    cropType: L("Potassium", "పొటాషియం", "पोटेशियम"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "50 kg", manufacturer: "Fertilizers India", seller: "Krishi Bazaar", price: 1700, availability: "in", delivery: "2–4 days" },
  { id: "fert-micronutrient", category: "fertilizers", image: I.micronutrient,
    name: L("Micronutrient Mix", "సూక్ష్మపోషక మిశ్రమం", "सूक्ष्म पोषक मिश्रण"),
    desc: L("Zinc, boron, iron & manganese mix.", "జింక్, బోరాన్, ఐరన్, మాంగనీస్ మిశ్రమం.", "जिंक, बोरॉन, लोहा और मैंगनीज़ मिश्रण।"),
    cropType: L("Micronutrient", "సూక్ష్మపోషకం", "सूक्ष्म पोषक"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "5 kg", manufacturer: "MicroGrow", seller: "AgriHub", price: 650, availability: "in", delivery: "2–4 days" },
  { id: "fert-organic", category: "fertilizers", image: I.organic,
    name: L("Organic Manure", "సేంద్రియ ఎరువు", "जैव खाद"),
    desc: L("Composted organic manure for soil health.", "నేల ఆరోగ్యానికి సేంద్రియ కంపోస్ట్ ఎరువు.", "मिट्टी स्वास्थ्य के लिए जैव कंपोस्ट खाद।"),
    cropType: L("Organic", "సేంద్రియం", "जैविक"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "25 kg", manufacturer: "EarthRoot", seller: "GreenGrow Mart", price: 400, availability: "in", delivery: "2–4 days" },
  { id: "fert-biofert", category: "fertilizers", image: I.biofert,
    name: L("Bio-fertilizer", "జీవ ఎరువు", "जैव उर्वरक"),
    desc: L("Nitrogen-fixing rhizobium bio-fertilizer.", "నత్రజని స్థిరీకరణ రైజోబియం జీవ ఎరువు.", "नाइट्रोजन स्थिरीकरण राइजोबियम जैव उर्वरक।"),
    cropType: L("Bio-fertilizer", "జీవ ఎరువు", "जैव उर्वरक"), season: L("Pulses & legumes", "పప్పు & పప్పుజన్యులు", "दलहन"),
    packSize: "1 kg", manufacturer: "BioFarm", seller: "AgriHub", price: 220, availability: "in", delivery: "3–5 days" },
  { id: "fert-watersoluble", category: "fertilizers", image: I.watersoluble,
    name: L("Water-Soluble Fertilizer", "నీటిలో కరిగే ఎరువు", "जल घुलनशील उर्वरक"),
    desc: L("100% soluble for drip & foliar application.", "డ్రిప్, ఆకు పిచికారానికి 100% కరిగే ఎరువు.", "ड्रिप और पत्ती छिडकाव के लिए 100% घुलनशील।"),
    cropType: L("Water-soluble", "నీటిలో కరిగే", "जल घुलनशील"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "5 kg", manufacturer: "YaraVera", seller: "Krishi Bazaar", price: 1800, availability: "in", delivery: "2–4 days" },

  // ---------------- CROP PROTECTION ----------------
  { id: "cp-biopesticide", category: "crop-protection", image: I.biopesticide,
    name: L("Bio-Pesticide", "జీవ పురుగుమందు", "जैव कीटनाशक"),
    desc: L("Eco-friendly neem-based bio-pesticide.", "పర్యావరణ అనుకూల వేప ఆధారిత జీవ పురుగుమందు.", "पर्यावरण अनुकूल नीम-आधारित जैव कीटनाशक।"),
    cropType: L("Bio-pesticide", "జీవ పురుగుమందు", "जैव कीटनाशक"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "1 L", manufacturer: "GreenGuard", seller: "AgriHub", price: 450, availability: "in", delivery: "2–4 days",
    note: "Use only according to approved label directions and expert agricultural advice." },
  { id: "cp-fungicide", category: "crop-protection", image: I.fungicide,
    name: L("Fungicide", "శిలీంధ్ర నాశకం", "फफूंदनाशक"),
    desc: L("Broad-spectrum fungicide for fungal control.", "శిలీంధ్ర నియంత్రణకు విస్తృత శిలీంధ్ర నాశకం.", "फंगल नियंत्रण के लिए व्यापक फफूंदनाशक।"),
    cropType: L("Fungicide", "శిలీంధ్ర నాశకం", "फफूंदनाशक"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "500 g", manufacturer: "CropCare", seller: "Krishi Bazaar", price: 380, availability: "in", delivery: "2–4 days",
    note: "Use only according to approved label directions and expert agricultural advice." },
  { id: "cp-herbicide", category: "crop-protection", image: I.herbicide,
    name: L("Herbicide", "కలుపు నాశకం", "खरपतवार नाशी"),
    desc: L("Pre-emergent herbicide for weed control.", "కలుపు నియంత్రణకు అంకుర-పూర్వ కలుపు నాశకం.", "खरपतवार नियंत्रण के लिए पूर्व-उद्भव खरपतवार नाशी।"),
    cropType: L("Herbicide", "కలుపు నాశకం", "खरपतवार नाशी"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "1 L", manufacturer: "CropCare", seller: "AgriHub", price: 520, availability: "in", delivery: "2–4 days",
    note: "Use only according to approved label directions and expert agricultural advice." },
  { id: "cp-insecticide", category: "crop-protection", image: I.insecticide,
    name: L("Insecticide", "పురుగు నాశకం", "कीटनाशक"),
    desc: L("Systemic insecticide for sucking pests.", "పీల్చే పురుగుల కోసం వ్యవస్థిత పురుగు నాశకం.", "चूसक कीटों के लिए व्यवस्थित कीटनाशक।"),
    cropType: L("Insecticide", "పురుగు నాశకం", "कीटनाशक"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "500 ml", manufacturer: "GreenGuard", seller: "Krishi Bazaar", price: 410, availability: "in", delivery: "2–4 days",
    note: "Use only according to approved label directions and expert agricultural advice." },
  { id: "cp-plantdisease", category: "crop-protection", image: I.plantdisease,
    name: L("Plant Disease Management", "మొక్క వ్యాధి నిర్వహణ", "पादप रोग प्रबंधन"),
    desc: L("Combo for bacterial & viral disease control.", "బాక్టీరియా & వైరల్ వ్యాధి నియంత్రణ కాంబో.", "जीवाणु और वायरल रोग नियंत्रण का कॉम्बो।"),
    cropType: L("Disease Mgmt", "వ్యాధి నిర్వహణ", "रोग प्रबंधन"), season: L("All crops", "అన్ని పంటలు", "सभी फसलें"),
    packSize: "1 L", manufacturer: "CropCare", seller: "AgriHub", price: 480, availability: "in", delivery: "2–4 days",
    note: "Use only according to approved label directions and expert agricultural advice." },
];

export function loc(field, lang) {
  if (!field) return "";
  return field[lang] || field.en;
}

export function productsByCategory(cat) {
  return PRODUCTS.filter((p) => p.category === cat);
}

export function getProduct(id) {
  return PRODUCTS.find((p) => p.id === id);
}